### ISSUE TITLE
Crash with duplicate insertion and ON CONFLICT DO NOTHING with Postgres.

### ISSUE THREAD

**Issue by baszalmstra** [SeaQL/sea-orm#1175] opened 2022-10-31 13:09 UTC
## Description

When inserting an entry in Postgres with an `ON CONFLICT DO NOTHING` twice the `exec_insert` method fails.

## Steps to Reproduce

Running the following query twice with the same value will yield no return result in the second run:

```sql
INSERT INTO
          "url" ("url")
        VALUES
          ($1) ON CONFLICT ("url") DO NOTHING RETURNING "id"
```

However, the function `exec_insert` expects a return value to exist on line `119` of `src/executor/insert.rs`. When running the query twice the program will crash with:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\sea-orm-0.10.1\src\executor\insert.rs:119:54
```

The sea-orm code that was used is:

```rust
url::Entity::insert_many(insertable_urls.clone())
        .on_conflict(OnConflict::column(url::Column::Url).do_nothing().to_owned())
        .exec(db)
        .await;
```

### Expected Behavior

I expect this query to work fine.

### Actual Behavior

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\sea-orm-0.10.1\src\executor\insert.rs:119:54
```

### Reproduces How Often

Every time

## Versions

sea-orm 0.10.1 

(Note that the above shortcut to past in the console doesn't work in powershell)

**Comment by billy1624** [comment] 2022-11-04 10:17
Hey @baszalmstra, thanks for the report!! I think this issue is a duplicate of
- https://github.com/SeaQL/sea-orm/issues/899

I'll look at both issue together. Thanks!!

**Closed** 2022-11-21 14:21 UTC
