### ISSUE TITLE
Make `DatabaseConnection` `Clone` with the default features enabled

### ISSUE THREAD

**Issue by 05storm26** [SeaQL/sea-orm#438] opened 2022-01-08 10:27 UTC
Some frameworks like actix_web require app global datas to be clonable. Currently one can only disable the `mock` feature to fix this. It would be great if `sea_orm::DatabaseConnection` could be clonable in all cases.

Currently the `mock` feature is by default enabled and that causes the `sea_orm::DatabaseConnection` to not implement `Clone` by default, because `MockDatabaseConnection` (which is a variant of `DatabaseConnection`) is not clonable.

**Comment by tyt2y3** [comment] 2022-01-08 11:33
I think the problem is `sea-orm` cannot build without at least one backend. We could either enable `sqlx-all` or `mock` by default, and I chose the latter because enabling all database backends by default will bloat the build time and binary size (if I only enable say `mysql`, it feels pretty biased too). It's thus necessary for users to add `default-features = false`.

**Comment by 05storm26** [comment] 2022-01-08 11:35
I think my point is that we should make `MockDatabaseConnection` implement `Clone`.

**Comment by tyt2y3** [comment] 2022-01-08 11:41
That would in theory work too, but another problem is there is no good way to model a MockDatabase if we allow concurrent access to it. Like the transaction log will be interleaved and probably be quite confusing.

I think the best solution is to allow `sea-orm` to at least build itself without any features enabled (and without any backend).

**Comment by alper** [comment] 2022-01-15 23:19
This was a huge gotcha for me trying to make the axum example work. 

If you don't add `default-features = false`, you get exactly this error and it's very hard to figure out how to fix it. Diving into the Connections, all of them do derive Clone.

**Closed** 2022-03-06 14:57 UTC

**Comment by hhstore** [comment] 2022-06-30 04:04
- `mock` conflicts with `axum route`.
- I just disable the `mock` feature, Indeed, solved the problem. 
- Curious about this feature, what does it do?

**Comment by billy1624** [comment] 2022-06-30 05:45
Hey @hhstore, if you don't need mock testing you can disable `mock` feature. However, if you do need it, please check https://github.com/SeaQL/sea-orm/issues/830

**Comment by NateAGeek** [comment] 2024-01-24 04:44
I believe the proposed solution might not be the most effective one, as it doesn't accommodate various project architectures where the 'core' and 'API' components share the same codebase. While I recognize the potential issues with making Mock cloneable, such as the risk of concurrent access, it seems counterproductive to limit developers' flexibility in structuring their projects for the sake of mock testing. I think we need to find a balance that supports diverse project structures without compromising on testing capabilities.
