### ISSUE TITLE
Support for mysql type DATE

### ISSUE THREAD

**Issue by efrain2007** [SeaQL/sea-orm#213] opened 2021-09-30 05:14 UTC
use chrono::NaiveDate;
use sea_orm::entity::prelude::*;
use sea_orm::DeriveEntityModel;

#[derive(Debug, Clone, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "currency_exchange_rate")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub currency_exchange_rate_id: i64,
    pub from_currency: String,
    pub to_currency: String,
    pub rate_date: NaiveDate,
    pub rate: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

**Comment by billy1624** [comment] 2021-09-30 06:02
Hey @efrain2007, we are working on the support of `chrono::Date` on #207.

Duplicate of #206.

**Closed** 2021-09-30 14:52 UTC

**Comment by tyt2y3** [comment] 2021-10-01 04:46
[0.2.4](https://github.com/SeaQL/sea-orm/releases/tag/0.2.4)
