### ISSUE TITLE
Compilation error when building with sqlx-sqlite and runtime-async-std-rustls

### ISSUE THREAD

**Issue by jsalort** [SeaQL/sea-orm#2192] opened 2024-04-10 14:16 UTC
## Description

An empty project with sea-orm as the only dependency fails to build when sqlx-sqlite and runtime-async-std-rustls are selected.

## Steps to Reproduce

Add the following to `Cargo.toml` in an empty project.
```
[dependencies]
sea-orm = { version = "0.12", features = [ "sqlx-sqlite", "runtime-async-std-rustls", "macros"] }
```

Then `cargo build` yields a number of errors while compiling sqlx-sqlite dependency.
I am not sure if this is a sea-orm bug (not selecting the correct features of sqlx), or a bug in sqlx.

## Versions
rustc 1.77.1

```
└── sea-orm v0.12.15
    ├── sea-orm-macros v0.12.15 (proc-macro)
    │   ├── sea-bae v0.2.0 (proc-macro)
    ├── sea-query v0.30.7
    ├── sea-query-binder v0.5.0
    │   ├── sea-query v0.30.7 (*)
```

**Comment by Expurple** [comment] 2024-04-14 12:03
I even had this error in CI for #2194. The log there should contain all necessary info

**Comment by tyt2y3** [comment] 2024-04-14 18:45
This is caused by https://github.com/launchbadge/sqlx/issues/3189 the fix's been merged, but not released yet.

**Comment by tyt2y3** [comment] 2024-04-14 22:11
Fixed with https://github.com/SeaQL/sea-query/releases/tag/0.31.0-rc.5

**Closed by tyt2y3** 2024-04-14 22:11 UTC
