### ISSUE TITLE
Use returning on databases which support it on ActiveModel::Save method

### ISSUE THREAD

**Issue by marlon-sousa** [SeaQL/sea-orm#188] opened 2021-09-22 22:12 UTC
Hello,

By investigating the save() method behavior I see that if it decides it is doing an insert two database operations are performed:

* insert
*  select, based on the id of the just inserted record.

Although this seems to be the only way of doing that for databases which does not support returning clauses, this causes a huge performance loss for databases which do support it, because if returning * is issued then only one connection needs to be performed.

I know that this is known, but I am recording this issue here for tracking.

**Comment by tyt2y3** [comment] 2021-09-23 07:52
Yes. I see that you have made other proposals too, and I'd go through them soon.

This one I think is affirmative, and I agree to use a returning clause where appropriate (now that latest SQLite has it too).

If you want to start working on a PR, I think this could be a good one.

**Comment by marlon-sousa** [comment] 2021-09-23 13:51
Hello,

I can work on that.

If you do not mind I will post questions here related to the general design before implementing.

## Features

I think we can assume that every time postgees is used as back-end returning shall be used.

As far as I know, one can not enable multiple back-ends on the same project, so that if postgres feature is activated then we will use returning.

But for mysql and sqlit things are more complicated, because both support returning, but this is version deppendant.

What I was thinking though is that we can create anopther feature called something like use_returning that is always enabled in case of postgres, but which can be enabled or disabled in case of other databases and document on the affected functions instructing the user to enable it in case sqlit is above version x or mysql is above version y ... either this or we enable it by default and ask the user to disable it in sqlit below version x or mysql  below version y. What do you think?

Because I see no other way since we can't know at compile time what db version will be used...

Thanks!

**Comment by tyt2y3** [comment] 2021-09-24 03:59
I think the first step would be extend the `Inserter` to support a returning clause.

Then, we can use this new feature to implement `ActiveModel::insert`.

We dont need a new feature flag, I think it will be similar to the mechanism, check the database backend and handle accordingly.

https://github.com/SeaQL/sea-orm/blob/6861802a6d9c6eabe554cb984a56d55dca7b2e62/src/executor/insert.rs#L89-L105

**Comment by tyt2y3** [comment] 2021-09-24 10:29
Is this a duplicate of #183 ?
If so, can we merge the two threads?

**Comment by marlon-sousa** [comment] 2021-09-24 12:18
I would say that this is a subset of #183. Being so, I think we can extend #183  scope to also include save() on it.

About the feature flag, I asked because, again, we know for sure that postgres supports returning. Other supported RDB' s also support it, but not all versions. So if I implement returning for mysql, for example, it will work if mysql above version 10 is used, but not otherwise. Same thing with sqlit. How should we handle this particular situation?

1. If we force returning sea-ql will no longer be compatible with a wide range of versions of mysql and sqlit.
2. If we plug in returning onluy for postgres, we will make users of modern versions of mysql and sqlit suffer from performance hits that they don't needto.

**Comment by billy1624** [comment] 2021-09-24 12:27
I would prefer having returning support for Postgres out of the box (not feature gated) and having extra db hits for MySQL and SQLite. Then, we provide feature gated returning support for MySQL and SQLite for those who wants it.

**Comment by marlon-sousa** [comment] 2021-09-24 12:38
Seems good.

**Comment by tyt2y3** [comment] 2021-10-01 04:42
Closed to consolidate with #183

**Closed by tyt2y3** 2021-10-01 04:42 UTC
