### ISSUE TITLE
Add upsert method for `EntityTrait`

### ISSUE THREAD

**Issue by GreenYun** [SeaQL/sea-orm#560] opened 2022-03-01 02:45 UTC
## Summary

Add upsert method for `EntityTrait`

## Motivation

It is useful and SQL database servers have such query syntax to do this.

## Additional Information

PostgreSQL: [INSERT](https://www.postgresql.org/docs/current/sql-insert.html)
SQLite: [upsert](https://www.sqlite.org/lang_UPSERT.html)
MySQL:  [INSERT ... ON DUPLICATE KEY UPDATE Statement](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html)

**Comment by billy1624** [comment] 2022-03-24 04:14
I'll close this now as this is a duplicate of #412

**Closed by billy1624** 2022-03-24 04:14 UTC
