### ISSUE TITLE
Insert & Update Return `Model` instead of `ActiveModel`

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#327] opened 2021-11-19 09:46 UTC
I wonder, since RETURNING support the methods return ActiveModels, wouldn't it be better to just return Models instead ? ActiveModel is better suited for inputs and Model for output, and it would make things more aligned with select. Also it is easy to convert from Model into ActiveModel, but not the other way around

It would also open possibility for convergence with QuerySelect/Select traits, so that we can write:

```rust
fruit::Entity::update(orange.clone())
        .filter(fruit::Column::Name.contains("orange"))
        .column_as(fruit::Column::Name, "foo")
        .into_model::<MyOrangeModel>()
        .exec(&db)
        .await
```

*Originally posted by @nicoulaj on Discord*

**Comment by billy1624** [comment] 2021-11-19 09:47
You made a good point! One blocker is that `ActiveModelBehavior`'s `before_*` & `after_*` operations takes `ActiveModel` instead of Model. https://docs.rs/sea-orm/0.3.2/sea_orm/entity/trait.ActiveModelBehavior.html

I guess we could do is to change `before_*` taking `ActiveModel`, while `after_*` taking `Model`.

How is that sounds?

**Comment by tyt2y3** [comment] 2021-11-19 10:57
duplicate of #289

**Closed by tyt2y3** 2021-11-19 10:57 UTC
