### ISSUE TITLE
0.10.6: still issues with `conflicting implementations of trait`

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1333] opened 2022-12-23 16:23 UTC
Since https://github.com/SeaQL/sea-orm/issues/1287 is closed I just tried 0.10.6: unfortunately the issue is still there:

```rust
impl Related<super::tenant::Entity> for Entity {
    fn to() -> RelationDef {
        super::house::Relation::Tenant.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::house::Relation::Player.def().rev())
    }
}

impl Related<super::tenant::Entity> for Entity {
    fn to() -> RelationDef {
        super::offer::Relation::Tenant.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::offer::Relation::Player.def().rev())
    }
}
```

with error:

```log
error[E0119]: conflicting implementations of trait `sea_orm::Related<generated::tenant::Entity>` for type `generated::player::Entity`
  --> src\entities\player.rs:65:1
   |
56 | impl Related<super::tenant::Entity> for Entity {
   | ---------------------------------------------- first implementation here
...
65 | impl Related<super::tenant::Entity> for Entity {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `generated::player::Entity`

error[E0119]: conflicting implementations of trait `sea_orm::Related<generated::player::Entity>` for type `generated::tenant::Entity`
   --> src\entities\tenant.rs:135:1
    |
117 | impl Related<super::player::Entity> for Entity {
    | ------------------------------------------------ first implementation here
...
135 | impl Related<super::player::Entity> for Entity {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `generated::tenant::Entity`
```

The entities in this case are:

```
Player {
    pub tenant_id: String,
}

House {
    pub tenant_id: String,
    pub player_id: String,
}

Offer {
    pub tenant_id: String,
    pub player_id: String,
}
```

I'll downgrade to 0.10.2 for now.

On other entites there is the same issue too (because of tenant_id).

**Comment by billy1624** [comment] 2023-01-21 15:27
Hey @frederikhors, sorry for the delay. I was not able to reproduce the error. Could you please provide a sample SQL like below?

```sql
create table if not exists player
(
    id integer
);

create unique index if not exists player_id_uindex
    on player (id);

create table if not exists tenant
(
    id integer
);

create unique index if not exists tenant_id_uindex
    on tenant (id);

create table if not exists house
(
    tenant_id integer
        constraint house_tenant_id_fk
            references tenant (id),
    player_id integer
        constraint house_player_id_fk
            references player (id)
);

create table if not exists offer
(
    tenant_id integer
        constraint offer_tenant_id_fk
            references tenant (id),
    player_id integer
        constraint offer_player_id_fk
            references player (id)
);
```

<img width="506" alt="image" src="https://user-images.githubusercontent.com/30400950/213873808-1bcb8d6b-821e-43b8-b4a5-2b91e6dfed6a.png">

**Comment by frederikhors** [comment] 2023-01-25 17:02
I'll in a few hours. Sorry for the delay.

**Comment by billy1624** [comment] 2023-01-25 22:38
Thanks!! @frederikhors No rush!

**Comment by ryanoillataguerre** [comment] 2023-01-29 22:32
+1 to this, blocking my migration to sea-orm at the moment :/

![Screenshot 2023-01-29 at 2 30 53 PM](https://user-images.githubusercontent.com/28904005/215359342-df84511e-a49c-40e8-a278-6a1f1566ebbd.png)

![Screenshot 2023-01-29 at 2 30 30 PM](https://user-images.githubusercontent.com/28904005/215359346-1f237011-7474-4a03-a316-906bf6152f65.png)

![Screenshot 2023-01-29 at 2 31 54 PM](https://user-images.githubusercontent.com/28904005/215359375-4dce64f5-1ff7-498d-9f56-cafeb5fff391.png)

**Comment by frederikhors** [comment] 2023-01-29 22:36
@ryanoillataguerre, can you post your sql? I cannot right now since I switched project.

**Comment by ryanoillataguerre** [comment] 2023-01-29 22:49
Hey @frederikhors good idea, here it is below:
```sql
CREATE TABLE users
(
  id uuid  PRIMARY KEY  DEFAULT uuid_generate_v1mc(),
  email TEXT UNIQUE NOT NULL,
  ...
);
```

```sql

  id uuid  PRIMARY KEY  DEFAULT uuid_generate_v1mc(),
  ...
);
```
```sql
CREATE TABLE users_votes
(
  user_id uuid REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  bill_id uuid REFERENCES bills (id) ON UPDATE CASCADE ON DELETE CASCADE,
  vote boolean NOT NULL,
  CONSTRAINT users_bills_pkey PRIMARY KEY (user_id, bill_id)
);
```

```sql
CREATE TABLE users_saved_bills
(
  user_id uuid REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  bill_id uuid REFERENCES bills (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT users_saved_bills_pkey PRIMARY KEY (user_id, bill_id)
);
```

**Comment by ryanoillataguerre** [comment] 2023-01-29 23:01
Is there another way to define these many to manies that I'm not catching in my SQL?

**Comment by billy1624** [comment] 2023-01-30 10:41
Thanks everyone for the help!! Please check this PR
- https://github.com/SeaQL/sea-orm/pull/1435

**Comment by ryanoillataguerre** [comment] 2023-02-01 01:44
> Thanks everyone for the help!! Please check this PR
> 
> * [Generate entity for duplicated many-to-many paths #1435](https://github.com/SeaQL/sea-orm/pull/1435)

This is awesome, thanks @billy1624 ! Hope it gets merged soon.

Out of curiosity, does this problem only show up for non-`sea-orm` migration-defined tables?  Like if I were to rewrite my migrations in Rust how the Getting Started guide does it, would this conflict not happen?

**Closed** 2023-04-13 03:16 UTC
