### ISSUE TITLE
[FR] Should we derive `Eq` as well?

### ISSUE THREAD

**Issue by frederikhors** [SeaQL/sea-orm#1037] opened 2022-09-12 10:22 UTC
## Motivation

I generated the first entity with SeaORM.

But Clippy is telling me this:

![image](https://user-images.githubusercontent.com/41120635/189630437-5045371e-8af9-4128-820d-48b5a572bf91.png)

## Proposed Solutions

Should we derive `Eq` as well?

**Comment by tyt2y3** [comment] 2022-09-13 01:38
We have to make sure there is no f64 in the entity in order to add that.

**Comment by billy1624** [comment] 2022-09-13 04:02
Hey @frederikhors, thanks for the feature request! We notice this new clippy lint has been stabilized. We're working on it, please check the PR at https://github.com/SeaQL/sea-orm/pull/988

Duplicate of https://github.com/SeaQL/sea-orm/issues/965

**Comment by billy1624** [comment] 2022-09-13 04:03
Duplicate of https://github.com/SeaQL/sea-orm/issues/965

**Closed** 2022-09-13 08:39 UTC
